Update publications.json
OpenMobileAlliance/technical.openmobilealliance.org pull request #181
Opened 2024-01-17 16:47 UTC by gocadimic

3 ETSs added to 'publication' file:

- ETS LwM2M v1.0.2, [OMA-ETS-LightweightM2M-V1_0_2-20180815-A.zip](https://openmobilealliance.org/release/LightweightM2M/ETS/OMA-ETS-LightweightM2M-V1_0_2-20180815-A.zip)

- ETS LwM2M v1.1, [OMA-ETS-LightweightM2M-V1_1-20190912-D.pdf](https://openmobilealliance.org/release/LightweightM2M/ETS/OMA-ETS-LightweightM2M-V1_1-20190912-D.pdf), and

- ETS LwM2M v1.2, [OMA-ETS-LightweightM2M_INT-V1_2-20231003-A.pdf](https://openmobilealliance.org/release/LightweightM2M/ETS/OMA-ETS-LightweightM2M_INT-V1_2-20231003-A.pdf)

2024-01-17 16:49 UTC, gocadimic commented
@jpradocueva,
Please check the updates, especially the descriptions in all three documents. I couldn't relate that with the given example, v.1.0.1.

2024-01-17 17:56 UTC, jpradocueva commented on publications.json
> +    "description": "This document describes in detail available test cases for LightweightM2M as specified in OMA-TS-LightweightM2M-V1_0. The test cases are split in two categories, conformance and i
@gocadimic This description is better to take it from the Introduction. We don't do Conformance test cases. Therefore, this description doesn't provide any input. The content in the Introduction session is better and provides further information.

2024-01-17 17:57 UTC, jpradocueva requested changes
@gocadimic, change the description to the content in the Introduction section of the document. It is more relevant as I mentioned on my inline comments.

2024-01-19 02:23 UTC, jpradocueva approved these changes
@gocadimic approved. Ready to merge.

2024-01-19 09:12 UTC, merged